version: "3.9"

services:
  filebrowser:
    image: gtstef/filebrowser:latest
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - FILEBROWSER_ADMIN_PASSWORD=${FILEBROWSER_ADMIN_PASSWORD}
    volumes:
      - /mnt/cephfs/docker-shared-data/filebrowser/config:/config # Configuration files - allow running on any node
      - /mnt/cephfs/docker-shared-data/filebrowser/data:/data      # User files - allow running on any node
      - /mnt/cephfs:/srv/cephfs # Access to CephFS storage
      - /mnt/nfs/media:/srv/media # Access to NFS media storage
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.filebrowser.rule=Host(`files.${DOMAIN}`)"
        - "traefik.http.routers.filebrowser.entrypoints=websecure"
        - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare"
        - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

        # Homepage
        - "homepage.group=Storage"
        - "homepage.name=FileBrowser"
        - "homepage.icon=filebrowser.png"
        - "homepage.href=https://files.${DOMAIN}"
        - "homepage.description=Cloud File Manager"
        - "homepage.server=my-docker"
        - "homepage.service=filebrowser_filebrowser"
        - "homepage.url=http://filebrowser_filebrowser:80"
        # - "homepage.widget.type=filebrowser"
        # - "homepage.widget.url=http://filebrowser_filebrowser:80"
        # - "homepage.widget.username=admin"
        # - "homepage.widget.password=${FILEBROWSER_ADMIN_PASSWORD}"

networks:
  proxy:
    external: true
