theme:
  background-color: "225 14% 15%"
  primary-color: "157 47% 65%"
  contrast-multiplier: 1.1

pages:
  - name: Dashboard
    columns:
      - size: small
        widgets:
          - type: clock
            time-format: "15:04"
          - type: calendar
          - type: weather
            location: London, United Kingdom
      - size: full
        widgets:
          - type: search
          - type: hacker-news
            limit: 15
            collapse-after: 10
          - type: bookmarks
            groups:
              - title: Infrastructure
                links:
                  - title: Traefik
                    url: https://traefik.${DOMAIN}
                  - title: Portainer
                    url: https://portainer.${DOMAIN}
                  - title: Beszel
                    url: https://beszel.${DOMAIN}
                  - title: Gatus
                    url: https://status.${DOMAIN}
              - title: Development
                links:
                  # - title: GitLab
                  #   url: https://git.${DOMAIN}
                  - title: FileBrowser
                    url: https://files.${DOMAIN}
                  - title: Docmost
                    url: https://doc.${DOMAIN}
              - title: Apps
                links:
                  - title: Homepage
                    url: https://home.${DOMAIN}
                  - title: Wallos
                    url: https://wallos.${DOMAIN}
                  - title: Whoami
                    url: https://whoami.${DOMAIN}

      - size: small
        widgets:
          - type: monitor
            title: Service Health
            cache: 1m
            services:
              - name: Traefik
                url: https://traefik.${DOMAIN}
              - name: Portainer
                url: https://portainer.${DOMAIN}
              - name: Homepage
                url: https://home.${DOMAIN}
              - name: GitLab
                url: https://git.${DOMAIN}
              # - name: Docmost
              #   url: https://doc.${DOMAIN}
              - name: FileBrowser
                url: https://files.${DOMAIN}
              - name: Gatus
                url: https://status.${DOMAIN}
          - type: docker-containers
            hide-by-default: false
