- Management:
    - Portainer:
        icon: portainer.png
        href: https://portainer.krapulax.net
        description: Docker Management
        server: my-docker
        service: portainer_portainer
        url: http://portainer_portainer:9000/api/system/status
        widget:
          type: portainer
          url: http://portainer_portainer:9000
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_ACCESS_TOKEN}}

- Storage:
    - FileBrowser:
        icon: filebrowser.png
        href: https://files.krapulax.net
        description: Cloud File Manager
        server: my-docker
        service: filebrowser_filebrowser
        url: http://filebrowser_filebrowser:80
        widget:
          type: filebrowser
          url: http://filebrowser_filebrowser:80
          username: admin
          password: {{HOMEPAGE_VAR_FILEBROWSER_ADMIN_PASSWORD}}