- Management:
    - Portainer:
        icon: portainer.png
        href: https://portainer.krapulax.net
        description: Docker Management
        server: my-docker
        service: portainer_portainer
        url: http://portainer_portainer:9000/api/system/status
        widget:
          type: portainer
          url: http://portainer_portainer:9000
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_ACCESS_TOKEN}}
