[[stack]]
name = "arr-support"
tags = ["homelab", "media"]

[stack.config]
server = "hl-media-debian"
project_name = "arr-stack"
poll_for_updates = true
files_on_host = true
run_directory = "/homelab/docker/arr-stack"
file_paths = [
  "docker-compose.extended.yml",
  "docker-compose.autobrr.yml"
]
extra_args = ["--force-recreate"]
