[[stack]]
name = "arr-stack"
description = "Arr* Apps"
tags = ["media", "homelab"]

[stack.config]
server = "hl-media-debian"
project_name = "arr-stack"
poll_for_updates = true
files_on_host = true
run_directory = "/homelab/docker/arr-stack"
file_paths = [
  "docker-compose.vpn.yml",
  "docker-compose.downloaders.yml",
  "docker-compose.arrs.yml"
]
