---
# Handlers for github_runner role

- name: "restart github runner"
  ansible.builtin.systemd:
    name: "actions.runner.{{ github_runner_service_name }}.service"
    state: restarted
    daemon_reload: yes
  become: true
