---
# defaults file for proxmox_vm

# Proxmox Settings
proxmox_node: "pve-2"
template_vm_id: 9008
default_vlan: 30

# VM Definitions
vms:
  - name: "dkr-srv-1"
    vm_id: 3011
    ipv4_address: "10.0.30.11/24"
    ipv4_gateway: "10.0.30.1"
    memory: 4096
    cores: 2
    disk_storage: "ceph-proxmox-rbd"
    disk_size: "30G"

  - name: "dkr-srv-2"
    vm_id: 3012
    ipv4_address: "10.0.30.12/24"
    ipv4_gateway: "10.0.30.1"
    memory: 4096
    cores: 2
    disk_storage: "ceph-proxmox-rbd"
    disk_size: "30G"