# Main admin user
admin_user: fs
sudo_nopasswd: true
domain_name: krapulax.dev

# list of packages to be installed
install_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - htop
  - unzip
  - git
  - dnsutils