theme:
  background-color: "225 14% 15%"
  primary-color: "157 47% 65%"
  contrast-multiplier: 1.1

pages:
  - name: Dashboard
    columns:
      - size: small
        widgets:
          - type: clock
            time-format: "15:04"
          - type: calendar
          - type: weather
            location: London, United Kingdom
      
      - size: full
        widgets:
          - type: search
          - type: bookmarks
            groups:
              - title: Infrastructure
                links:
                  - title: Traefik
                    url: https://traefik.krapulax.dev
                  - title: Whoami
                    url: https://whoami.krapulax.dev
                  - title: Portainer
                    url: https://portainer.krapulax.dev
                  - title: Dockpeek
                    url: https://dockpeek.krapulax.dev
          
          - type: monitor
            title: Service Health
            cache: 1m
            services:
              - name: Traefik
                url: https://traefik.krapulax.dev
              - name: Whoami
                url: https://whoami.krapulax.dev
              - name: Dockpeek
                url: https://dockpeek.krapulax.dev

      - size: small
        widgets:
          - type: hacker-news
            limit: 10
            collapse-after: 5
          - type: docker-containers
            hide-by-default: false
