version: "3.9"

services:
  glance:
    image: glanceapp/glance:v0.8.4
    networks:
      - proxy
    configs:
      - source: glance_config
        target: /app/config/glance.yml
    volumes:
      - glance-data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          memory: 64M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.glance.rule=Host(`glance.${DOMAIN}`)"
        - "traefik.http.routers.glance.entrypoints=websecure"
        - "traefik.http.routers.glance.tls.certresolver=cloudflare"
        - "traefik.http.services.glance.loadbalancer.server.port=8080"

        # Homepage
        - "homepage.group=Utilities"
        - "homepage.name=Glance"
        - "homepage.icon=glance.png"
        - "homepage.href=https://glance.${DOMAIN}"
        - "homepage.description=Startpage"

configs:
  glance_config:
    file: ./config/glance.yml

volumes:
  glance-data:

networks:
  proxy:
    external: true