theme:
  background-color: "#1a1b26"
  primary-color: "#7aa2f7"
  positive-color: "#9ece6a"
  negative-color: "#f7768e"

pages:
  - name: Dashboard
    columns:
      - size: small
        widgets:
          - type: calendar
          - type: clock
          - type: weather
            location: London, United Kingdom
      - size: full
        widgets:
          - type: search
          - type: bookmarks
            groups:
              - name: Infrastructure
                links:
                  - name: Traefik
                    url: https://traefik.krapulax.dev
                  - name: Whoami
                    url: https://whoami.krapulax.dev
          - type: monitor
            cache: 1m
            services:
              - name: Traefik
                url: https://traefik.krapulax.dev
              - name: Whoami
                url: https://whoami.krapulax.dev
