theme:
  background-color: "237 18% 13%"
  primary-color: "220 89% 72%"
  positive-color: "90 49% 61%"
  negative-color: "349 89% 72%"

pages:
  - name: Dashboard
    columns:
      - size: small
        widgets:
          - type: calendar
          - type: clock
          - type: weather
            location: London, United Kingdom
      - size: full
        widgets:
          - type: search
          - type: bookmarks
            groups:
              - name: Infrastructure
                links:
                  - name: Traefik
                    url: https://traefik.krapulax.dev
                  - name: Whoami
                    url: https://whoami.krapulax.dev
          - type: monitor
            cache: 1m
            services:
              - name: Traefik
                url: https://traefik.krapulax.dev
              - name: Whoami
                url: https://whoami.krapulax.dev