version: "3.9"

services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    environment:
      - LISTEN=45876
      - "KEY=${BESZEL_AGENT_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host:ro
    ports:
      - "45876:45876"
    restart: unless-stopped
