services:
  dozzle:
    image: amir20/dozzle:latest
    labels:
      - "prometheus.io/scrape=false"
    hostname: 'logs.${DOMAIN}'
    environment:
      - "TZ=${TZ}"
      - "DOZZLE_REMOTE_HOST=tcp://socket-proxy:2375"
    networks:
      - proxy
      - socket-proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.rule=Host(`logs.${DOMAIN}`)"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.tls.certresolver=cloudflare"
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

        # Homepage Discovery
        - "homepage.group=Management"
        - "homepage.name=Dozzle"
        - "homepage.icon=dozzle.png"
        - "homepage.href=https://logs.${DOMAIN}"
        - "homepage.description=Docker Log Viewer"

networks:
  proxy:
    external: true
  socket-proxy:
    external: true
