services:
  dozzle:
    image: amir20/dozzle:latest
    labels:
      - "prometheus.io/scrape=false"
    hostname: 'logs.${DOMAIN}'
    environment:
      - "TZ=${TZ}"
      - "DOZZLE_MODE=swarm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.rule=Host(`logs.${DOMAIN}`)"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.tls.certresolver=cloudflare"
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

        # Homepage Discovery
        - "homepage.group=Management"
        - "homepage.name=Dozzle"
        - "homepage.icon=dozzle.png"
        - "homepage.href=https://logs.${DOMAIN}"
        - "homepage.description=Docker Log Viewer"

networks:
  proxy:
    external: true
