---
- name: Site Preflight Check and Update
  hosts: all
  
  pre_tasks:
    - name: Ping all hosts
      ping:

  roles:
    - system_update

  post_tasks:
    - name: Verify hosts are back online and get OS family
      debug:
        msg: "Host {{ inventory_hostname }} is online. OS Family: {{ ansible_os_family }}"