---
all:
  children:
    home_vms:
      hosts:
        dkr-srv-1:
          ansible_host: 10.0.30.11
        dkr-srv-2:
          ansible_host: 10.0.30.12
      vars:
        ansible_user: fs
        ansible_ssh_private_key_file: ~/.ssh/fs_home_rsa
    cloud_vms:
      hosts:
        dkr-srv-0:
          ansible_host: 157.180.84.140
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_fs_hetzner
    swarm_managers:
      children:
        home_vms:
        cloud_vms:
