name: Generate Terraform Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform_infra/modules/**'
      - 'terraform_apps/**'
  pull_request:
    paths:
      - 'terraform_infra/modules/**'
      - 'terraform_apps/**'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Terraform docs (hetzner-cloud)
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: terraform_infra/modules/hetzner-cloud
          output-file: README.md
          output-method: inject
          git-push: ${{ github.event_name == 'push' }}


      - name: Terraform docs (proxmox-vm)
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: terraform_infra/modules/proxmox-vm
          output-file: README.md
          output-method: inject
          git-push: ${{ github.event_name == 'push' }}

      - name: Terraform docs (terraform_apps)
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: terraform_apps
          output-file: README.md
          output-method: inject
          git-push: ${{ github.event_name == 'push' }}
