---
- name: Deploy Portainer
  hosts: cloud_vms
  become: true
  roles:
    - portainer

  post_tasks:
    - name: "Show Completion Message"
      run_once: true
      ansible.builtin.debug:
        msg:
          - "=================================================="
          - "ðŸš¢ PORTAINER DEPLOYMENT COMPLETE"
          - "   â€¢ Portainer Agent running"
          - "   â€¢ UI available"
          - "=================================================="
